FROM python:3.7.3-alpine3.10
LABEL maintainer="sjquant (seonujang92@gmail.com)"

RUN apk add --no-cache bash && apk --no-cache add tzdata && \
        cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
        echo "Asia/Seoul" > /etc/timezone && \
        apk add --no-cache libpq postgresql-dev && \
        apk add --no-cache  build-base

# 컨테이너 재생성시 바이너리 파일이 없어지는 문제 수정
ENV PYTHONHASHSEED=random \
  PYTHONUNBUFFERED=0

RUN pip install --upgrade pip
COPY ./scripts /app/scripts
WORKDIR /app
RUN chmod +x scripts/*.sh