FROM python:3.8-slim
LABEL maintainer="sjquant (seonujang92@gmail.com)"
RUN apt-get update -y && apt-get install build-essential -y
# timezone
RUN cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
  echo "Asia/Seoul" > /etc/timezone
ENV PYTHONHASHSEED=random \
  PYTHONUNBUFFERED=1
RUN pip install --upgrade pip && pip install poetry==1.0.5
RUN poetry config virtualenvs.create false
COPY ./scripts /workspace/scripts
WORKDIR /workspace
RUN chmod +x scripts/*.sh