### Search By English
GET http://localhost:8000/lines/search/english/Hello Engster
Content-Type: application/json

### Search By Korean 2
GET http://localhost:8000/lines/search/korean/안녕 Engster
Content-Type: application/json

### Search Context
GET http://localhost:8000/lines/search/context/1
Content-Type: application/json