### Convert File (smi)
POST http://localhost:8000/admin/lines/convert_subtitle
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="input"; filename="Inside Out.smi"
Content-Type: text/plain

< D:/SJ/engster/subtitles/InsideOut.smi
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="output"

InsideOutKor.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Convert File (srt)
POST http://localhost:8000/admin/lines/convert_subtitle
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="input"; filename="Inside Out.srt"
Content-Type: text/plain

< D:/SJ/engster/subtitles/InsideOut.srt
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="output"

InsideOutEng.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Combine eng and kor and Convert them to single file
POST http://localhost:8000/admin/lines/combine_convert
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="input_eng"; filename="Inside Out.srt"
Content-Type: text/plain

< D:/SJ/engster/subtitles/InsideOut.srt
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="input_kor"; filename="Inside Out.smi"
Content-Type: text/plain

< D:/SJ/engster/subtitles/InsideOut.smi
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="output"

InsideOut.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Upload Content
POST http://localhost:8000/admin/lines/upload_content
Content-Type: application/json

{
    "title": "The Maze Runner",
    "year": "2014",
    "reference": "",
    "category_id": 1,
    "genre_ids": [4, 10, 11, 14]
}

### Upload Eng Subtitle (Maze Runner)
POST http://localhost:8000/admin/lines/upload_eng_subtitle/19
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="input_file"; filename="TheMazeRunner.csv"
Content-Type: text/csv

< D:/SJ/engster/processed/TheMazeRunner.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Upload Kor Subtitle
POST http://localhost:8000/admin/lines/upload_kor_subtitle/19
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="input_file"; filename="TheMazeRunner.csv"
Content-Type: text/csv

< D:/SJ/engster/processed/TheMazeRunner.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--