### Register
POST {{ host }}/auth/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefg!!!"
}

### Obtain Token
# @name obtainToken
POST {{ host }}/auth/obtain-token
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefg!!!"
}

### Refresh Token
POST {{ host }}/auth/refresh-token
Content-Type: application/json

### Get user profile
GET {{ host }}/auth/profile
Content-Type: application/json

### update user profile
PUT {{ host }}/auth/profile
Content-Type: application/json

{
    "email": "seonu97@gmail.com"
}

### reset user password
PUT {{ host }}/auth/reset-password
Content-Type: application/json

{
    "original_password": "1234!",
    "new_password": "12345!"
}
