### GET Likes for a Line
GET http://localhost:8000/like/english/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiL

### Like English Line
POST http://localhost:8000/like/english/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzAyNzQ0ODEsIm5iZiI6MTU3MDI3NDQ4MSwianRpIjoiYTkyZWUwMjYtNWMxOC00ZTU4LWJlNGUtMDFmMTdlYmJlNTVhIiwiZXhwIjo4Nzk3MDE4ODA4MSwiaWRlbnRpdHkiOiI0NDg2OGYyNC1mNmMxLTQ3YzYtYjFhMS0xYzBjNmQwNjRhNWQiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.Lq0ZYg4jvgblT4Dt28kYxTJDFO5lkh3hrN0s05DjMXs

### Cancel the like of English Line
DELETE http://localhost:8000/like/english/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzAyNzQ0ODEsIm5iZiI6MTU3MDI3NDQ4MSwianRpIjoiYTkyZWUwMjYtNWMxOC00ZTU4LWJlNGUtMDFmMTdlYmJlNTVhIiwiZXhwIjo4Nzk3MDE4ODA4MSwiaWRlbnRpdHkiOiI0NDg2OGYyNC1mNmMxLTQ3YzYtYjFhMS0xYzBjNmQwNjRhNWQiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.Lq0ZYg4jvgblT4Dt28kYxTJDFO5lkh3hrN0s05DjMXs

### GET Likes for a Korean Line
GET http://localhost:8000/like/korean/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiL

### Like Korean Line
POST http://localhost:8000/like/korean/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzAyNzQ0ODEsIm5iZiI6MTU3MDI3NDQ4MSwianRpIjoiYTkyZWUwMjYtNWMxOC00ZTU4LWJlNGUtMDFmMTdlYmJlNTVhIiwiZXhwIjo4Nzk3MDE4ODA4MSwiaWRlbnRpdHkiOiI0NDg2OGYyNC1mNmMxLTQ3YzYtYjFhMS0xYzBjNmQwNjRhNWQiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.Lq0ZYg4jvgblT4Dt28kYxTJDFO5lkh3hrN0s05DjMXs

### Cancel the like of Korean Line
DELETE http://localhost:8000/like/korean/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzAyNzQ0ODEsIm5iZiI6MTU3MDI3NDQ4MSwianRpIjoiYTkyZWUwMjYtNWMxOC00ZTU4LWJlNGUtMDFmMTdlYmJlNTVhIiwiZXhwIjo4Nzk3MDE4ODA4MSwiaWRlbnRpdHkiOiI0NDg2OGYyNC1mNmMxLTQ3YzYtYjFhMS0xYzBjNmQwNjRhNWQiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.Lq0ZYg4jvgblT4Dt28kYxTJDFO5lkh3hrN0s05DjMXs

