## Variables
@userid = 09e18ddb-cb3b-400c-9e82-627b8b205025

### Get user activities
GET http://localhost:8000/my-page/{{userid}}/activity-summary
Content-Type: application/json

### Get Lines a user liked
GET http://localhost:8000/my-page/{{userid}}/liked-english-lines?page=1
Content-Type: application/json

### Get Translations a user liked
GET http://localhost:8000/my-page/{{userid}}/liked-korean-lines?page=2
Content-Type: application/json

### Get Translations a user created
GET http://localhost:8000/my-page/{{userid}}/translations?page=1
Content-Type: application/json