### Variables
@userid = {{ siginin.response.body.$.user.id }}

### Sign In
# @name siginin
POST {{ host }}/auth/obtain-token
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefg!!!"
}

### Get user activities
GET {{ host }}/my-page/{{userid}}/activity-summary
Content-Type: application/json

### Get Lines a user liked
GET {{ host }}/my-page/{{userid}}/liked-english-lines?limit=20
Content-Type: application/json

### Get Translations a user liked
GET {{ host }}/my-page/{{userid}}/liked-korean-lines?limit=20
Content-Type: application/json

### Get Translations a user created
GET {{ host }}/my-page/{{userid}}/translations?limit=20
Content-Type: application/json