## Variables
@userid = 7f825548-3c7d-4f0d-8ab7-9c4682443080

### Get Lines a user liked
GET http://localhost:8000/my-page/{{userid}}/line-likes/english?page=1
Content-Type: application/json

### Get Translations a user liked
GET http://localhost:8000/my-page/{{userid}}/line-likes/korean?page=2
Content-Type: application/json

### Get Translations a user created
GET http://localhost:8000/my-page/{{userid}}/translations?page=1
Content-Type: application/json