### Variables
@userid = {{ siginin.response.body.$.user.id }}

### Sign In
# @name siginin
POST {{ host }}/auth/obtain-token
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefg!!!"
}

### Sign In with admin
# @name siginin
POST {{ host }}/auth/obtain-token
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "abcdefg!!!"
}

### Randomly pick subtitles
GET {{ host }}/subtitles/random?max_count=30
Content-Type: application/json

### Search By English
GET {{ host }}/subtitles/search?keyword=minho
Content-Type: application/json

### Like subtitles
POST {{ host }}/subtitles/1/like
Content-Type: application/json

### Unlike subtitles
DELETE {{ host }}/subtitles/1/like
Content-Type: application/json


### Fetch Translations for a subtitle
GET {{ host }}/subtitles/800/translations
Content-Type: application/json

### Create Translation
# @name createTranslation
POST {{ host }}/subtitles/800/translations
Content-Type: application.json

{
    "translation": "무슨 일?"
}