### Variables
@userid = {{ siginin.response.body.$.user.id }}

### Sign In
# @name siginin
POST {{ host }}/auth/obtain-token
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefg!!!"
}

### Sign In with admin
# @name siginin
POST {{ host }}/auth/obtain-token
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "abcdefg!!!"
}


### Fetch content subtitles
GET {{ host }}/subtitles?content_id=1
Content-Type: application/json


### Upload subtitles
POST {{ host }}/subtitles?content_id=1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="input"; filename="TheMazeRunner.csv"
Content-Type: text/csv

< ../data/csv/TheMazeRunner.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW

### Download subtitle files as csv
POST {{ host }}/subtitles/download-as-csv
Content-Type: application/json

{
    "content_id": 1
}


### Convert subtitle files into csv
POST {{ host }}/subtitles/convert-to-csv
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="subtitle"; filename="InsideOut.srt"
Content-Type: text/plain

< ../data/subtitles/InsideOut.srt
------WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="translation"; filename="InsideOut.smi"
Content-Type: text/plain

< ../data/subtitles/InsideOut.smi
------WebKitFormBoundary7MA4YWxkTrZu0gW

### Randomly pick subtitles
GET {{ host }}/subtitles/random?max_count=30
Content-Type: application/json

### Search subtitles
GET {{ host }}/subtitles/search?keyword=minho
Content-Type: application/json

### Like subtitles
POST {{ host }}/subtitles/1/like
Content-Type: application/json

### Unlike subtitles
DELETE {{ host }}/subtitles/1/like
Content-Type: application/json


### Fetch Translations for a subtitle
GET {{ host }}/subtitles/800/translations
Content-Type: application/json

### Create Translation
# @name createTranslation
POST {{ host }}/subtitles/800/translations
Content-Type: application.json

{
    "translation": "무슨 일?"
}

### Get User-liked subtitles
GET {{ host }}/subtitles/liked?user_id={{userid}}&limit=20
Content-Type: application/json