@userid = {{ siginin.response.body.$.user.id }}

### Obtain Token
# @name siginin
POST {{ host }}/auth/obtain-token
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefg!!!"
}

### Sign In with admin
# @name siginin
POST {{ host }}/auth/obtain-token
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "abcdefg!!!"
}


### Get Specific translation
GET {{ host }}/translations/1423

### Change specific translation
PATCH {{ host }}/translations/1423

{
    "translation": "민호야 힘내!"
}

### Delete specific translation
DELETE {{ host }}/translations/2181


### Search Translations
GET {{ host }}/translations/search?keyword=위험
Content-Type: application/json


### Like translation
POST {{ host }}/translations/1/like
Content-Type: application/json

### Unlike translation
DELETE {{ host }}/translations/1/like
Content-Type: application/json

### Get Translations a user liked
GET {{ host }}/translations/liked?user_id={{userid}}&limit=20
Content-Type: application/json

### Get Translations a user created
GET {{ host }}/translations/written?user_id={{userid}}&limit=20
Content-Type: application/json

### Change translation status
POST {{ host }}/translations/15530/change-status
Content-Type: application/json

{
    "status": "CHANGE_REQUESTED",
    "message": "오타가 있습니다. hpapy -> happy로 바꿔주시면 좋을거 같습니다."
}

### Get reveiews for a translation
GET {{ host }}/translations/15530/reviews?limit=5
Content-Type: application/json