"""empty message

Revision ID: 0bb8d248b8a0
Revises: 046e93cf2e1f
Create Date: 2020-10-19 01:46:14.150540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb8d248b8a0'
down_revision = '046e93cf2e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('poster', sa.String(length=255), nullable=True))
    op.drop_column('content', 'reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('content', 'poster')
    # ### end Alembic commands ###
