"""empty message

Revision ID: 16d211094d8d
Revises: 409a4c93af5f
Create Date: 2019-04-29 02:20:48.857721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d211094d8d'
down_revision = '409a4c93af5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
