"""empty message

Revision ID: 22418d8642b4
Revises: 2cb2021a6b91
Create Date: 2020-01-04 00:17:31.112693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22418d8642b4'
down_revision = '2cb2021a6b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('is_issued', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('main_content', sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('main_content', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('main_content', 'lines')
    op.drop_column('main_content', 'is_issued')
    # ### end Alembic commands ###
