"""empty message

Revision ID: 27f113bd4f5f
Revises: c766dc0d8d62
Create Date: 2021-04-24 02:34:15.879763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f113bd4f5f'
down_revision = 'c766dc0d8d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('line_like_user_id_fkey', 'line_like', type_='foreignkey')
    op.drop_constraint('line_like_line_id_fkey', 'line_like', type_='foreignkey')
    op.create_foreign_key(None, 'line_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'line_like', 'subtitle', ['line_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('translation_user_id_fkey', 'translation', type_='foreignkey')
    op.drop_constraint('translation_line_id_fkey', 'translation', type_='foreignkey')
    op.create_foreign_key(None, 'translation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'translation', 'subtitle', ['line_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('translation_like_translation_id_fkey', 'translation_like', type_='foreignkey')
    op.drop_constraint('translation_like_user_id_fkey', 'translation_like', type_='foreignkey')
    op.create_foreign_key(None, 'translation_like', 'translation', ['translation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'translation_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('translation_review_translation_id_fkey', 'translation_review', type_='foreignkey')
    op.create_foreign_key(None, 'translation_review', 'translation', ['translation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translation_review', type_='foreignkey')
    op.create_foreign_key('translation_review_translation_id_fkey', 'translation_review', 'translation', ['translation_id'], ['id'])
    op.drop_constraint(None, 'translation_like', type_='foreignkey')
    op.drop_constraint(None, 'translation_like', type_='foreignkey')
    op.create_foreign_key('translation_like_user_id_fkey', 'translation_like', 'user', ['user_id'], ['id'])
    op.create_foreign_key('translation_like_translation_id_fkey', 'translation_like', 'translation', ['translation_id'], ['id'])
    op.drop_constraint(None, 'translation', type_='foreignkey')
    op.drop_constraint(None, 'translation', type_='foreignkey')
    op.create_foreign_key('translation_line_id_fkey', 'translation', 'subtitle', ['line_id'], ['id'])
    op.create_foreign_key('translation_user_id_fkey', 'translation', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'line_like', type_='foreignkey')
    op.drop_constraint(None, 'line_like', type_='foreignkey')
    op.create_foreign_key('line_like_line_id_fkey', 'line_like', 'subtitle', ['line_id'], ['id'])
    op.create_foreign_key('line_like_user_id_fkey', 'line_like', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
