"""empty message

Revision ID: 5e41fc06d136
Revises: 848ba89f69ea
Create Date: 2019-04-24 02:44:47.193535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e41fc06d136'
down_revision = '848ba89f69ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(),
                                    server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(),
                                    server_default=sa.text('now()'), nullable=True))
    op.drop_column('user', 'registered_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_on',
                                    postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
