"""empty message

Revision ID: 6b75e017e18a
Revises: 9bf560d35565
Create Date: 2020-09-20 00:15:03.373283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b75e017e18a'
down_revision = '9bf560d35565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('content_idx_id', 'content', ['id'], unique=False)
    op.create_index('content_idx_title', 'content', ['title'], unique=False)
    op.create_unique_constraint('content_genre_unique', 'content_genre', ['content_id', 'genre_id'])
    op.create_index('line_idx_id', 'line', ['id'], unique=False)
    op.create_index('translation_idx_id', 'translation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('translation_idx_id', table_name='translation')
    op.drop_index('line_idx_id', table_name='line')
    op.drop_constraint('content_genre_unique', 'content_genre', type_='unique')
    op.drop_index('content_idx_title', table_name='content')
    op.drop_index('content_idx_id', table_name='content')
    # ### end Alembic commands ###
