"""add constraints

Revision ID: 98909f087cc8
Revises: 16d211094d8d
Create Date: 2019-04-29 14:42:38.295641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98909f087cc8'
down_revision = '16d211094d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('line_idx_line', 'line', ['line'], unique=False)
    op.create_unique_constraint('line_like_unique', 'line_like', ['user_id', 'line_id'])
    op.create_index('translation_idx_translation', 'translation', ['translation'], unique=False)
    op.create_unique_constraint('translation_like_unique', 'translation_like', ['user_id', 'translation_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('translation_like_unique', 'translation_like', type_='unique')
    op.drop_index('translation_idx_translation', table_name='translation')
    op.drop_constraint('line_like_unique', 'line_like', type_='unique')
    op.drop_index('line_idx_line', table_name='line')
    # ### end Alembic commands ###
