"""empty message

Revision ID: acb8152af6f6
Revises: 61694f14294e
Create Date: 2019-05-12 00:24:46.407708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb8152af6f6'
down_revision = '61694f14294e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('translation_content_id_fkey', 'translation', type_='foreignkey')
    op.drop_column('translation', 'content_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation', sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('translation_content_id_fkey', 'translation', 'content', ['content_id'], ['id'])
    # ### end Alembic commands ###
