"""empty message

Revision ID: c4122aa10aaf
Revises: d01f4f8512c3
Create Date: 2019-12-21 23:45:31.550704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4122aa10aaf'
down_revision = 'd01f4f8512c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_contents',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_contents')
    # ### end Alembic commands ###
