"""empty message

Revision ID: c69a4fdbf0a7
Revises: 30f57e0cdc6b
Create Date: 2020-11-29 22:38:43.288963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c69a4fdbf0a7"
down_revision = "30f57e0cdc6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("line", "subtitle")
    op.alter_column(
        "subtitle",
        "time",
        existing_type=postgresql.TIME(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="extract(epoch from time)",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("subtitle", "line")
    op.alter_column(
        "line",
        "time",
        existing_type=sa.Integer(),
        type_=postgresql.TIME(),
        existing_nullable=True,
        postgresql_using="to_timestamp(time)::time",
    )
    # ### end Alembic commands ###


