"""empty message

Revision ID: ddbd1c7b6626
Revises: cc2d7f59b913
Create Date: 2019-03-09 12:37:07.864533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbd1c7b6626'
down_revision = 'cc2d7f59b913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation', sa.Column('content_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'translation', 'content', ['content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translation', type_='foreignkey')
    op.drop_column('translation', 'content_id')
    # ### end Alembic commands ###
