"""modifiy content-genre

Revision ID: 36d9eb38905a
Revises: 7087854352ac
Create Date: 2019-01-27 19:40:45.813977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d9eb38905a'
down_revision = '7087854352ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_genre', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_genre', 'id')
    # ### end Alembic commands ###
