"""change password col to password_hash

Revision ID: 45110046e2a5
Revises: 818d533a6a93
Create Date: 2019-01-20 21:10:06.564979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45110046e2a5'
down_revision = '818d533a6a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
