"""empty message

Revision ID: 718732552a36
Revises: 6aec45941991
Create Date: 2019-02-01 22:34:23.467643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718732552a36'
down_revision = '6aec45941991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'user', ['nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
