"""empty message

Revision ID: 863bcb63021b
Revises: 550ef3a09e9a
Create Date: 2019-01-26 00:38:52.182330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863bcb63021b'
down_revision = '550ef3a09e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###
