"""empty message

Revision ID: 90d9d4ffd4e3
Revises: 2d7304526c55
Create Date: 2019-02-03 04:34:33.111094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d9d4ffd4e3'
down_revision = '2d7304526c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('content_genre', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('content_genre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('line', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('translation', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('translation', 'line_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation', 'line_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('translation', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('line', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content_genre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content_genre', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
