"""add timestampedmodel

Revision ID: bfc8bd91458a
Revises: 02da007ba281
Create Date: 2019-03-01 02:05:55.314153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc8bd91458a'
down_revision = '02da007ba281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_like', sa.Column('created_at', sa.DateTime(),
                                         server_default=sa.text('now()'), nullable=True))
    op.add_column('line_like', sa.Column('updated_at', sa.DateTime(),
                                         server_default=sa.text('now()'), nullable=True))
    op.add_column('translation', sa.Column(
        'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('translation', sa.Column(
        'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('translation_like', sa.Column(
        'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('translation_like', sa.Column(
        'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_like', 'updated_at')
    op.drop_column('translation_like', 'created_at')
    op.drop_column('translation', 'updated_at')
    op.drop_column('translation', 'created_at')
    op.drop_column('line_like', 'updated_at')
    op.drop_column('line_like', 'created_at')
    # ### end Alembic commands ###
